import { useState } from 'react'
import { formatINR, type Expense, type ExpenseInput } from '../types/finance'
import { ExpenseForm } from './ExpenseForm'
import { Icon } from './Icon'

const categoryColors: Record<string, string> = { Housing: 'bg-[#293d25] text-[#b8eb8b]', Food: 'bg-[#243d3c] text-[#83ddd5]', Transport: 'bg-[#453726] text-[#ffc88b]', Shopping: 'bg-[#452c35] text-[#ff9dad]', Entertainment: 'bg-[#302d4c] text-[#b3aff2]', Health: 'bg-[#3a3020] text-[#f8d38d]' }

type ExpenseTableProps = { expenses: Expense[]; compact?: boolean; emptyTitle?: string; onUpdate?: (id: string, expense: ExpenseInput) => Promise<void>; onDelete?: (id: string) => Promise<void> }
const formatDate = (date: string) => new Date(`${date}T12:00:00`).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })

export function ExpenseTable({ expenses, compact = false, emptyTitle = 'No expenses yet', onUpdate, onDelete }: ExpenseTableProps) {
  const [editing, setEditing] = useState<Expense | null>(null)
  if (!expenses.length) return <div className="px-5 py-16 text-center"><p className="text-lg font-semibold text-white">{emptyTitle}</p><p className="mt-2 text-sm text-[#78837d]">Try changing your filters or add a new expense.</p></div>
  return <div className="overflow-x-auto">{editing && onUpdate && <div className="border-b border-[#d5f477]/20 bg-[#101a16] p-5"><div className="mb-4 flex items-center justify-between"><p className="font-semibold text-white">Editing expense</p><button aria-label="Close edit form" className="rounded-lg p-2 text-[#7d8781] hover:bg-white/8 hover:text-white" onClick={() => setEditing(null)} type="button">×</button></div><ExpenseForm initialExpense={editing} onCancel={() => setEditing(null)} onSubmit={(expense) => { onUpdate(editing.id, expense); setEditing(null) }} /></div>}<table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-white/8 text-[10px] font-semibold uppercase tracking-[0.15em] text-[#68736d]"><th className="px-5 py-3 font-medium">Date</th><th className="px-5 py-3 font-medium">Description</th><th className="px-5 py-3 font-medium">Category</th><th className="px-5 py-3 font-medium">Payment</th><th className="px-5 py-3 text-right font-medium">Amount</th>{!compact && <th className="px-5 py-3 text-right font-medium">Actions</th>}</tr></thead><tbody>{expenses.map((expense, index) => <tr className="expense-row border-b border-white/6 last:border-0" key={expense.id} style={{ animationDelay: `${index * 45}ms` }}><td className="px-5 py-4 text-sm text-[#8d9690]">{formatDate(expense.date)}</td><td className="px-5 py-4 text-sm font-medium text-[#e5e9e4]">{expense.description || 'Untitled expense'}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[11px] font-medium ${categoryColors[expense.category]}`}>{expense.category}</span></td><td className="px-5 py-4 text-xs text-[#89938d]">{expense.paymentMethod}</td><td className="px-5 py-4 text-right text-sm font-semibold text-[#f0f3ee]">{formatINR(expense.amount)}</td>{!compact && <td className="px-5 py-4"><div className="flex justify-end gap-1"><button aria-label={`Edit ${expense.description}`} className="rounded-lg p-2 text-[#7d8781] hover:bg-white/8 hover:text-white" onClick={() => setEditing(expense)} type="button"><Icon name="edit" size={15} /></button><button aria-label={`Delete ${expense.description}`} className="rounded-lg p-2 text-[#7d8781] hover:bg-[#3d2928] hover:text-[#ff9d8d]" onClick={() => window.confirm(`Delete ${expense.description || 'this expense'}?`) && onDelete?.(expense.id)} type="button"><Icon name="trash" size={15} /></button></div></td>}</tr>)}</tbody></table></div>
}
