import { useState } from 'react'
import { formatINR, type Income, type IncomeInput } from '../types/finance'
import { IncomeForm } from './IncomeForm'
import { Icon } from './Icon'

export function IncomeTable({ incomes, onUpdate, onDelete }: { incomes: Income[]; onUpdate: (id: string, income: IncomeInput) => Promise<void>; onDelete: (id: string) => Promise<void> }) {
  const [editing, setEditing] = useState<Income | null>(null)
  const sortedIncomes = [...incomes].sort((a, b) => b.date.localeCompare(a.date))
  if (!sortedIncomes.length) return <div className="px-5 py-16 text-center"><p className="text-lg font-semibold text-white">No income recorded</p><p className="mt-2 text-sm text-[#78837d]">Add your first income entry to start tracking your balance.</p></div>
  return <div className="overflow-x-auto">{editing && <div className="border-b border-[#d5f477]/20 bg-[#101a16] p-5"><div className="mb-4 flex items-center justify-between"><p className="font-semibold text-white">Editing income</p><button aria-label="Close edit form" className="rounded-lg p-2 text-[#7d8781] hover:bg-white/8 hover:text-white" onClick={() => setEditing(null)} type="button">×</button></div><IncomeForm initialIncome={editing} onCancel={() => setEditing(null)} onSubmit={(income) => { onUpdate(editing.id, income); setEditing(null) }} /></div>}<table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-white/8 text-[10px] font-semibold uppercase tracking-[0.15em] text-[#68736d]"><th className="px-5 py-3 font-medium">Date</th><th className="px-5 py-3 font-medium">Source</th><th className="px-5 py-3 font-medium">Description</th><th className="px-5 py-3 text-right font-medium">Amount</th><th className="px-5 py-3 text-right font-medium">Actions</th></tr></thead><tbody>{sortedIncomes.map((income, index) => <tr className="expense-row border-b border-white/6 last:border-0" key={income.id} style={{ animationDelay: `${index * 45}ms` }}><td className="px-5 py-4 text-sm text-[#8d9690]">{new Date(`${income.date}T12:00:00`).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</td><td className="px-5 py-4 text-sm font-medium text-[#e5e9e4]">{income.source}</td><td className="px-5 py-4 text-sm text-[#89938d]">{income.description || 'No description'}</td><td className="px-5 py-4 text-right text-sm font-semibold text-[#b8eb8b]">+{formatINR(income.amount)}</td><td className="px-5 py-4"><div className="flex justify-end gap-1"><button aria-label={`Edit ${income.source}`} className="rounded-lg p-2 text-[#7d8781] hover:bg-white/8 hover:text-white" onClick={() => setEditing(income)} type="button"><Icon name="edit" size={15} /></button><button aria-label={`Delete ${income.source}`} className="rounded-lg p-2 text-[#7d8781] hover:bg-[#3d2928] hover:text-[#ff9d8d]" onClick={() => window.confirm(`Delete ${income.source} income?`) && onDelete(income.id)} type="button"><Icon name="trash" size={15} /></button></div></td></tr>)}</tbody></table></div>
}
